In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
dict = {
    'Name' : ['Rahul','Pawan','Garvit','Jwala'],
    'Age' : [21,20,19,20],
    'city' : ['Mathura','Banda','Lucknow','Gorakhpur']
}

In [4]:
dict

{'Name': ['Rahul', 'Pawan', 'Garvit', 'Jwala'],
 'Age': [21, 20, 19, 20],
 'city': ['Mathura', 'Banda', 'Lucknow', 'Gorakhpur']}

In [5]:
Student_df = pd.DataFrame(dict)

In [6]:
Student_df

     Name  Age       city
0   Rahul   21    Mathura
1   Pawan   20      Banda
2  Garvit   19    Lucknow
3   Jwala   20  Gorakhpur

In [7]:
Student_df.columns

Index(['Name', 'Age', 'city'], dtype='object')

In [8]:
Student_df.Name

0     Rahul
1     Pawan
2    Garvit
3     Jwala
Name: Name, dtype: object

In [9]:
Student_df['city']

0      Mathura
1        Banda
2      Lucknow
3    Gorakhpur
Name: city, dtype: object

In [10]:
new_df = Student_df[['Name','city']]

In [11]:
new_df

     Name       city
0   Rahul    Mathura
1   Pawan      Banda
2  Garvit    Lucknow
3   Jwala  Gorakhpur

In [12]:
book_df = {
    'BOOK' : ['Physics','Maths','Descrete Maths'],
    'Auther' : ['HC Verma','RD Sharma','Manish Goyal'],
    'Price' : [100,200,300]

}

In [13]:
book_df = pd.DataFrame(book_df)

In [14]:
book_df

             BOOK        Auther  Price
0         Physics      HC Verma    100
1           Maths     RD Sharma    200
2  Descrete Maths  Manish Goyal    300

In [15]:
book_df["Publisher"] = "Penguin"

In [16]:
book_df

             BOOK        Auther  Price Publisher
0         Physics      HC Verma    100   Penguin
1           Maths     RD Sharma    200   Penguin
2  Descrete Maths  Manish Goyal    300   Penguin

In [17]:
book_df["SerialNo"] = np.arange(3)

In [18]:
book_df

             BOOK        Auther  Price Publisher  SerialNo
0         Physics      HC Verma    100   Penguin         0
1           Maths     RD Sharma    200   Penguin         1
2  Descrete Maths  Manish Goyal    300   Penguin         2

In [19]:
del book_df['SerialNo']

In [20]:
book_df

             BOOK        Auther  Price Publisher
0         Physics      HC Verma    100   Penguin
1           Maths     RD Sharma    200   Penguin
2  Descrete Maths  Manish Goyal    300   Penguin

In [25]:
data = {
    'Movie': ['3 Idiots', 'Dangal', 'PK'],
    'Year': [2009, 2016, 2014],
    'Rating': [8.4, 8.3, 8.1]
}

movie_df = pd.DataFrame(data)

movie_df

      Movie  Year  Rating
0  3 Idiots  2009     8.4
1    Dangal  2016     8.3
2        PK  2014     8.1

In [23]:
new_df = movie_df[['Movie', 'Rating']].copy()

new_df['Director'] = ['Rajkumar Hirani', 'Nitesh Tiwari', 'Rajkumar Hirani']

new_df

      Movie  Rating         Director
0  3 Idiots     8.4  Rajkumar Hirani
1    Dangal     8.3    Nitesh Tiwari
2        PK     8.1  Rajkumar Hirani

In [24]:
new_df = movie_df[['Movie', 'Rating']].copy()

new_df['Director'] = ['Rajkumar Hirani', 'Nitesh Tiwari', 'Rajkumar Hirani']

new_df

      Movie  Rating         Director
0  3 Idiots     8.4  Rajkumar Hirani
1    Dangal     8.3    Nitesh Tiwari
2        PK     8.1  Rajkumar Hirani

In [27]:
cities = pd.Series(
    ['Delhi', 'Mumbai'],
    index=[0, 3]
)

cities

0     Delhi
3    Mumbai
dtype: object

In [28]:
df = pd.DataFrame({
    'Student': ['Aman', 'Riya', 'Rahul', 'Priya']
})

cities = pd.Series(
    ['Delhi', 'Mumbai'],
    index=[0, 3]
)

df['Branch'] = cities

df

  Student  Branch
0    Aman   Delhi
1    Riya     NaN
2   Rahul     NaN
3   Priya  Mumbai

In [32]:
import io
import pandas as pd

# Paste your copied tabular data inside the triple quotes below:
copied_data = """Col1\tCol2
1\tA
2\tB"""

# Read the string data into a DataFrame (adjust the separator 'sep' if needed)
copied_df = pd.read_csv(io.StringIO(copied_data), sep='\t')

print(copied_df)

   Col1 Col2
0     1    A
1     2    B

In [33]:
data = {
    'Employee': ['Aman', 'Riya', 'Rahul', 'Priya', 'Karan'],
    'Department': ['IT', 'HR', 'Sales', 'IT', 'Finance'],
    'Experience': [2, 4, 3, 5, 1]
}

employee_df = pd.DataFrame(data)

new_df = employee_df[['Employee', 'Experience']]
new_df

  Employee  Experience
0     Aman           2
1     Riya           4
2    Rahul           3
3    Priya           5
4    Karan           1

In [34]:
employee_df['Department']
employee_df.columns

Index(['Employee', 'Department', 'Experience'], dtype='object')

In [35]:
employee_df['Office'] = 'Head Office'

employee_df

  Employee Department  Experience       Office
0     Aman         IT           2  Head Office
1     Riya         HR           4  Head Office
2    Rahul      Sales           3  Head Office
3    Priya         IT           5  Head Office
4    Karan    Finance           1  Head Office

In [36]:
employee_df['Office'] = np.arange(5)

employee_df

  Employee Department  Experience  Office
0     Aman         IT           2       0
1     Riya         HR           4       1
2    Rahul      Sales           3       2
3    Priya         IT           5       3
4    Karan    Finance           1       4

In [37]:
office_names = pd.Series(
    ['Delhi', 'Mumbai', 'Pune'],
    index=[0, 2, 4]
)

employee_df['Office'] = office_names

employee_df

  Employee Department  Experience  Office
0     Aman         IT           2   Delhi
1     Riya         HR           4     NaN
2    Rahul      Sales           3  Mumbai
3    Priya         IT           5     NaN
4    Karan    Finance           1    Pune

In [38]:
employee_df.drop(columns=['Office'], inplace=True)

employee_df

  Employee Department  Experience
0     Aman         IT           2
1     Riya         HR           4
2    Rahul      Sales           3
3    Priya         IT           5
4    Karan    Finance           1

In [39]:
data = {
    'Product': ['Laptop', 'Phone', 'Tablet'],
    'Category': ['Electronics', 'Electronics', 'Electronics'],
    'Price': [60000, 25000, 30000]
}

product_df = pd.DataFrame(data)

new_product_df = product_df[['Price', 'Product', 'Category']]

new_product_df

   Price Product     Category
0  60000  Laptop  Electronics
1  25000   Phone  Electronics
2  30000  Tablet  Electronics

In [40]:
data = {
    'Name': ['Aman', 'Riya', 'Rahul'],
    'Age': [20, 21, 19],
    'Marks': [85, 90, 78]
}

df = pd.DataFrame(data)

new_df = df.reindex(columns=['Name', 'Age', 'Marks', 'City'])

new_df

    Name  Age  Marks  City
0   Aman   20     85   NaN
1   Riya   21     90   NaN
2  Rahul   19     78   NaN

In [41]:
df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rahul'],
    'Total Marks': [85, 90, 78]
})

df['Total Marks']

0    85
1    90
2    78
Name: Total Marks, dtype: int64

In [43]:
import io
import pandas as pd

# Paste your copied tabular data inside the triple quotes:
copied_data = """Col1\tCol2
1\tA
2\tB"""

# Load the data into a DataFrame
copied_df = pd.read_csv(io.StringIO(copied_data), sep='\t')

print(copied_df.columns)

Index(['Col1', 'Col2'], dtype='object')

In [44]:
new_df = copied_df.iloc[:, :3]

new_df

   Col1 Col2
0     1    A
1     2    B

In [45]:
import pandas as pd
import numpy as np

data = {
    'Student': ['Aman', 'Riya', 'Rahul', 'Priya', 'Karan'],
    'Course': ['Python', 'Java', 'C++', 'Python', 'Java'],
    'Score': [85, 90, 78, 88, 92]
}

course_df = pd.DataFrame(data)

In [46]:

course_df.columns

Index(['Student', 'Course', 'Score'], dtype='object')

In [47]:


course_df['Student']

0     Aman
1     Riya
2    Rahul
3    Priya
4    Karan
Name: Student, dtype: object

In [48]:
new_df = course_df[['Student', 'Score']]
new_df

  Student  Score
0    Aman     85
1    Riya     90
2   Rahul     78
3   Priya     88
4   Karan     92

In [49]:
course_df['Batch'] = '2026'
course_df

  Student  Course  Score Batch
0    Aman  Python     85  2026
1    Riya    Java     90  2026
2   Rahul     C++     78  2026
3   Priya  Python     88  2026
4   Karan    Java     92  2026

In [50]:
data = {
    'Student': ['Aman', 'Riya', 'Rahul', 'Priya', 'Karan'],
    'Class': [10, 10, 12, 11, 12],
    'Section': ['A', 'B', 'A', 'C', 'B']
}

school_df = pd.DataFrame(data)


new_df = school_df.reindex(
    columns=['Student', 'Class', 'Section', 'House']
)

print(new_df)

new_df['House'] = 'Red House'

print(new_df)

  Student  Class Section  House
0    Aman     10       A    NaN
1    Riya     10       B    NaN
2   Rahul     12       A    NaN
3   Priya     11       C    NaN
4   Karan     12       B    NaN
  Student  Class Section      House
0    Aman     10       A  Red House
1    Riya     10       B  Red House
2   Rahul     12       A  Red House
3   Priya     11       C  Red House
4   Karan     12       B  Red House